logging.level.root: INFO

spring:
  application:
    name: car-parts-store
  jpa:
    hibernate:
      ddl-auto: none
      # Don't need to Hibernate to populate the database, Spring did it already

logging:
  level:
    org.springframework.security: TRACE

custom:
  security:
    jwt:
      token-timeout-min: ${TOKEN_TIMEOUT_MIN:60}
      refresh-token-timeout-min: ${REFRESH_TOKEN_TIMEOUT_MIN:86400} # 24 hours is the default.

      rsa-private-key: ${RSA_PRIVATE_KEY:}
      # Optional. If not provided, it will be generated.
      # Example generation of a new key pair: openssl genrsa -out keypair.pem 2048

      rsa-public-key: ${RSA_PUBLIC_KEY:}
      # Optional. If not provided, it will be generated.
      # Example to extract public key from a private key: openssl rsa -in keypair.pem -pubout -out public.pem