services:
  db:
    image: postgres:17.4-alpine
    restart: no
    container_name: postgres

    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=me
      - POSTGRES_DB=db
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:5.2.1
    restart: no
    container_name: adminer
    ports:
      - "8080:8080"